### ISSUE TITLE
Need Information this plugin and good example

### ISSUE THREAD

**Issue by bugfindr** [zakjan/mapbox-gl-draw-geodesic#2]
Hello,

Thanks for your replay. I really get confused so I have few questions.
1) What's relation of this library (mapbox-gl-draw-geodesic) and Leaflet.Geodesic? Since I have my existing code based on Leaflet.Geodesic.

2) Can you please prepare your example like example.html so we can see all required reference and available functions to draw geometry. 

3) What's is difference between (mapbox-gl-draw-geodesic) and Leaflet.Geodesic Or any drawback of this library?

Thanks!

**Comment by zakjan** [comment]
Hi @bugfindr,

This is a library for [Mapbox](https://github.com/mapbox/mapbox-gl-js) + [MapboxDraw](https://github.com/mapbox/mapbox-gl-draw). The example is available at https://github.com/zakjan/mapbox-gl-draw-geodesic/blob/master/docs/index.html and it is deployed at https://zakjan.github.io/mapbox-gl-draw-geodesic/

It's not supported to use mapbox-gl-draw-geodesic with Leaflet, or Leaflet.Geodesic with Mapbox.  I intervened with the Leaflet.Geodesic only because of we're facing similar underlying computation issues, and looked for if we could share the solution.
